def get_full_name(abbr):
    
    team_names_full = {
        'SF': 'San Francisco 49ers',
        'KC': 'Kansas City Chiefs',
        'ARI': 'Arizona Cardinals',
        'ATL': 'Atlanta Falcons',
        'BAL': 'Baltimore Ravens',
        'PHI': 'Philadelphia Eagles',
        'NYG': 'New York Giants',
        'NO': 'New Orleans Saints',
        'NE': 'New England Patriots',
        'MIN': 'Minnesota Vikings',
        'MIA': 'Miami Dolphins',
        'IND': 'Indianapolis Colts',
        'CLE': 'Cleveland Browns',
        'LAC': 'Los Angeles Chargers',
        'DEN': 'Denver Broncos',
        'CAR': 'Carolina Panthers',
        'GB': 'Green Bay Packers',
        'DET': 'Detroit Lions',
        'OAK': 'Oakland Raiders',
        'CIN': 'Cincinnati Bengals',
        'WAS': 'Washington Redskins',
        'TEN': 'Tennessee Titans',
        'TB': 'Tampa Bay Buccaneers',
        'PIT': 'Pittsburgh Steelers',
        'NYJ': 'New York Jets',
        'BUF': 'Buffalo Bills',
        'LA': 'Los Angeles Rams',
        'JAX': 'Jacksonville Jaguars',
        'DAL': 'Dallas Cowboys',
        'CHI': 'Chicago Bears',
        'HOU': 'Houston Texans',
        'SEA': 'Seattle Seahawks',
    }

    return team_names_full[abbr]

def get_short_name(abbr):
    
    team_names_short = {
        'SF': '49ers',
        'KC': 'Chiefs',
        'ARI': 'Cardinals',
        'ATL': 'Falcons',
        'BAL': 'Ravens',
        'PHI': 'Eagles',
        'NYG': 'Giants',
        'NO': 'Saints',
        'NE': 'Patriots',
        'MIN': 'Vikings',
        'MIA': 'Dolphins',
        'IND': 'Colts',
        'CLE': 'Browns',
        'LAC': 'Chargers',
        'DEN': 'Broncos',
        'CAR': 'Panthers',
        'GB': 'Packers',
        'DET': 'Lions',
        'OAK': 'Raiders',
        'CIN': 'Bengals',
        'WAS': 'Redskins',
        'TEN': 'Titans',
        'TB': 'Buccaneers',
        'PIT': 'Steelers',
        'NYJ': 'Jets',
        'BUF': 'Bills',
        'LA': 'Rams',
        'JAX': 'Jaguars',
        'DAL': 'Cowboys',
        'CHI': 'Bears',
        'HOU': 'Texans',
        'SEA': 'Seahawks',
    }
        
    return team_names_short[abbr]